# Generated by Django 2.0.4 on 2018-10-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamarziendan', '0003_auto_20181028_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='edition',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
    ]
