# Generated by Django 2.0.4 on 2018-10-29 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamarziendan', '0005_remove_artist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=ckeditor.fields.RichTextField(default='<p>Eaque nisi molestiae ab assumenda. Quia iusto consequatur consequuntur. Minus asperiores praesentium fuga aspernatur ut. Voluptatem rerum ut iure. Vel dicta voluptatibus et nisi hic. Exercitationem consectetur ea non a atque dolor blanditiis.</p><p>Doloremque facilis in minus est id debitis placeat. Quia in officia eos et. Omnis velit consequatur beatae enim reiciendis. Rerum voluptates modi in et consectetur rerum. Dolorem quibusdam hic voluptatem dolore sed doloribus unde quis. Sapiente quidem velit tenetur voluptatem magni.</p>', verbose_name='beschrijving'),
            preserve_default=False,
        ),
    ]
