# Generated by Django 2.0.4 on 2018-10-29 14:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lamarziendan', '0006_artist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='beschrijving'),
        ),
    ]
