# Generated by Django 2.0.4 on 2018-10-29 16:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lamarziendan', '0007_auto_20181029_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, verbose_name='nummer')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='lamarziendan.Edition', verbose_name='editie')),
            ],
            options={
                'verbose_name': 'Participatie',
                'verbose_name_plural': 'Participaties',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='naam')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='URL')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='beschrijving')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('links', models.TextField(blank=True, help_text='Plak hier per regel één hyperlink', verbose_name='social media links')),
            ],
            options={
                'verbose_name': 'Teamlid',
                'verbose_name_plural': 'Teamleden',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='participation',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='lamarziendan.TeamMember', verbose_name='teamlid'),
        ),
    ]
