# Generated by Django 2.0.4 on 2018-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamarziendan', '0009_auto_20181106_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='team_member',
        ),
        migrations.AddField(
            model_name='edition',
            name='participations',
            field=models.ManyToManyField(blank=True, related_name='editions', to='lamarziendan.TeamMember', verbose_name='teamleden'),
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
    ]
