# Generated by Django 2.0.4 on 2018-12-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamarziendan', '0010_auto_20181106_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='concept',
            field=models.BooleanField(default=False, verbose_name='concept'),
        ),
    ]
