# Generated by Django 2.0.4 on 2019-02-07 08:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lamarziendan', '0011_edition_concept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.PositiveIntegerField(choices=[(20, 'Footer')], unique=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Inhoud')),
            ],
            options={
                'verbose_name': 'configuratieparameter',
                'ordering': ['parameter'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('tagline', models.TextField(blank=True, verbose_name='tagline')),
                ('slug', models.SlugField(blank=True, help_text='Dit is een korte identifier om te gebruiken in URL’s. Deze moet uniek zijn. Gebruik bij voorkeur alleen kleine letters.', unique=True, verbose_name='URL')),
                ('menu', models.BooleanField(default=True, verbose_name='zichtbaar in het menu')),
                ('changed', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Pagina’s',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube, Vimeo, of SoundCloud link')),
                ('button', models.CharField(blank=True, max_length=255, verbose_name='button')),
                ('hyperlink', models.CharField(blank=True, max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lamarziendan.Page', verbose_name='pagina')),
            ],
            options={
                'verbose_name': 'sectie',
                'ordering': ['page', 'position'],
            },
        ),
    ]
