# Generated by Django 2.0.4 on 2019-02-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamarziendan', '0012_config_page_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('normal', 'Normaal'), ('banner', 'Banner'), ('contact', 'Contactformulier')], default='normal', help_text='Het soort sectie bepaalt hoe de sectie wordt weergegeven. Sommige soorten hebben extra functionaliteiten!', max_length=16, verbose_name='soort sectie'),
        ),
    ]
