# Generated by Django 2.0.4 on 2019-02-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamarziendan', '0013_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='titel'),
        ),
    ]
